baseURL = 'alireza-mandegar.github.io/DarkByte'
languageCode = 'en-us'
title = 'DarkByte'
theme = 'nightfall'

[menu]
[[menu.header]]
name = "posts"
weight = 0
url = "posts"


[params]
user = "DarkByte"
hostname = "github.io"
[params.author]
name = "Wellcome to DarkByte: Where Logs Confess and Endpoints Spill Their Secrets."
email = "Threat Not Found... For Now."

readingTime = true
published = true

[[params.social]]
key = 0
name = "github"
url = "https://github.com/alireza-mandegar"
target = "_blank"
aria = "GitHub Profile"

[[params.social]]
key = 2
name = "linkedin"
url = "https://www.linkedin.com/"
aria = "LinkedIn Profile"
